version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - db
    command: ["java", "-jar", "target/devcontainer-0.0.1-SNAPSHOT.jar"]

    #environment:
      #SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      #SPRING_DATASOURCE_USERNAME: postgres
      #SPRING_DATASOURCE_PASSWORD: postgres

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
